### ISSUE TITLE
Error en sedes

### ISSUE THREAD

**Issue by jbci** [ciudadanointeligente/partidopublico#17]
![error](https://cloud.githubusercontent.com/assets/17278568/17258405/b4222226-5594-11e6-891c-58fc4a7f3e80.png)

**Comment by jbci** [comment]
probablemente se debe a q no accedió a la app mediante la ruta /admin.
a la espera de confirmación.

**Comment by jdgarrido** [comment]
revisé, esa ruta no existe, osea, puedes acceder a ella, pero no es una ruta válida, quizás se debería deshabilitar.

**Comment by jdgarrido** [comment]
agregué la corrección de que al ir a /partido/:id te redirecciona al primer item del menú

**Comment by jbci** [comment]
se setea comuna en todas las sedes de todos los partidos.
ya no da error
