### ISSUE TITLE
Front - Representantes - Autoridades - Resultados elecciones Internas(Cargos Internos) - Candidatos - Declaracion de Intereses y Patrimonio

### ISSUE THREAD

**Issue by jbci** [ciudadanointeligente/partidopublico#21]
![representantes](https://cloud.githubusercontent.com/assets/17278568/18317842/b5ed97ae-74f5-11e6-8182-efb2497f3a18.png)

**Comment by jdgarrido** [comment]
en la rama dev se encuentran resueltas estas vistas
